### ISSUE TITLE
Online Sync

### ISSUE THREAD

**Issue by sbutz** [sbutz/poolscore#4]
**Goal**

The score should restore itself in case the computer shuts down.

**ToDo**

- [x] #22
  - [x] Login Page
  - [x] Protect routes which require login
- [x] #27
  - [x] Register Page (username, password, vereinsname)
  - [x] Create Club using Cloud Functions Auth Trigger
  - [x] Add firestore rules
  - [x] Disable in firebase console
  - [x] #30
  - [x] #28
- [x] Club Management
  - [x] #31
  - [x] #33
- [x] Table Management #50 
  - [x] create and update tables
  - [x] unique table names 
- [x] Different Logins for Admin and Tables #50
  - [x] Default claim for new user: admin
  - [x] Admin User can create a second Account without admin claim (which email to use?)
  - [x] Use Custom Tokens with restricted privleges
- [x] #52

**Comment by sbutz** [comment]
Matchay support continued in other issue.
